"""Add saved queries tables

Revision ID: d62aba489b61
Revises: 5d97b3468c6b
Create Date: 2026-07-01 19:07:12.042437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd62aba489b61'
down_revision: Union[str, None] = '5d97b3468c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_queries',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='The analysis session where this query was originally generated'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=False, comment='The original natural language question'),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('sql_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the normalized SQL for duplicate detection'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('execution_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_saved_queries_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], name=op.f('fk_saved_queries_session_id_analysis_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_saved_queries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_queries')),
    sa.UniqueConstraint('workspace_id', 'sql_hash', name='uq_workspace_sql_hash')
    )
    op.create_index(op.f('ix_saved_queries_deleted_at'), 'saved_queries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_saved_queries_id'), 'saved_queries', ['id'], unique=False)
    op.create_index(op.f('ix_saved_queries_session_id'), 'saved_queries', ['session_id'], unique=False)
    op.create_index(op.f('ix_saved_queries_sql_hash'), 'saved_queries', ['sql_hash'], unique=False)
    op.create_index(op.f('ix_saved_queries_workspace_id'), 'saved_queries', ['workspace_id'], unique=False)
    op.create_table('saved_query_runs',
    sa.Column('saved_query_id', sa.UUID(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment="'success' or 'failed'"),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['saved_query_id'], ['saved_queries.id'], name=op.f('fk_saved_query_runs_saved_query_id_saved_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_query_runs'))
    )
    op.create_index(op.f('ix_saved_query_runs_id'), 'saved_query_runs', ['id'], unique=False)
    op.create_index(op.f('ix_saved_query_runs_saved_query_id'), 'saved_query_runs', ['saved_query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_query_runs_saved_query_id'), table_name='saved_query_runs')
    op.drop_index(op.f('ix_saved_query_runs_id'), table_name='saved_query_runs')
    op.drop_table('saved_query_runs')
    op.drop_index(op.f('ix_saved_queries_workspace_id'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_sql_hash'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_session_id'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_id'), table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_deleted_at'), table_name='saved_queries')
    op.drop_table('saved_queries')
    # ### end Alembic commands ###
