"""add insight_data

Revision ID: 5d97b3468c6b
Revises: e6a1a0d5ffef
Create Date: 2026-07-01 18:32:40.684634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d97b3468c6b'
down_revision: Union[str, None] = 'e6a1a0d5ffef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('insight_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI-generated business insights from SQL execution results'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'insight_data')
    # ### end Alembic commands ###
