"""add generated_sql to messages

Revision ID: 085274df2abb
Revises: b7e1d04af382
Create Date: 2026-07-01 10:10:53.723038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '085274df2abb'
down_revision: Union[str, None] = 'b7e1d04af382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'description',
               existing_type=sa.VARCHAR(length=512),
               comment='Human-readable summary of the event',
               existing_nullable=False)
    op.alter_column('activity_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Structured event-specific context',
               existing_nullable=True)
    op.alter_column('analysis_sessions', 'goal',
               existing_type=sa.TEXT(),
               comment='User-defined objective or hypothesis for this session',
               existing_nullable=True)
    op.alter_column('analysis_sessions', 'status',
               existing_type=postgresql.ENUM('active', 'archived', name='sessionstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('datasets', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Original filename as uploaded by the user',
               existing_nullable=False)
    op.alter_column('datasets', 'storage_key',
               existing_type=sa.VARCHAR(length=1024),
               comment='Object storage path (S3 key, GCS object name, etc.)',
               existing_nullable=False)
    op.alter_column('datasets', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               server_default=None,
               comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('datasets', 'columns_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Per-column schema inferred during processing',
               existing_nullable=True)
    op.alter_column('datasets', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'ready', 'error', name='datasetstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('datasets', 'error_message',
               existing_type=sa.TEXT(),
               comment="Set when status = 'error'",
               existing_nullable=True)
    op.alter_column('generated_queries', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment="Human-readable label, e.g. 'Top 5 regions by sales'",
               existing_nullable=False)
    op.alter_column('generated_queries', 'is_saved',
               existing_type=sa.BOOLEAN(),
               comment='True when promoted to the workspace Query Library',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('messages', sa.Column('generated_sql', sa.Text(), nullable=True, comment='Extracted SQL query from the assistant response'))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='Full message text — may include markdown',
               existing_nullable=False)
    op.alter_column('messages', 'has_sql',
               existing_type=sa.BOOLEAN(),
               comment='True when the AI response contains a SQL block',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment="AI model identifier, e.g. 'gpt-4o', 'claude-3-5-sonnet-20241022'",
               existing_nullable=True)
    op.alter_column('messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment='Total tokens consumed (prompt + completion)',
               existing_nullable=True)
    op.alter_column('saved_visualizations', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Chart renderer options (axes, colours, labels, legend)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('saved_visualizations', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array of data-point objects as returned by the query',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('saved_visualizations', 'is_saved',
               existing_type=sa.BOOLEAN(),
               comment='True when promoted to the workspace Analytics gallery',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_visualizations', 'is_saved',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True when promoted to the workspace Analytics gallery',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('saved_visualizations', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Array of data-point objects as returned by the query',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('saved_visualizations', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Chart renderer options (axes, colours, labels, legend)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total tokens consumed (prompt + completion)',
               existing_nullable=True)
    op.alter_column('messages', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="AI model identifier, e.g. 'gpt-4o', 'claude-3-5-sonnet-20241022'",
               existing_nullable=True)
    op.alter_column('messages', 'has_sql',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True when the AI response contains a SQL block',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full message text — may include markdown',
               existing_nullable=False)
    op.drop_column('messages', 'generated_sql')
    op.alter_column('generated_queries', 'is_saved',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True when promoted to the workspace Query Library',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('generated_queries', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Human-readable label, e.g. 'Top 5 regions by sales'",
               existing_nullable=False)
    op.alter_column('datasets', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Set when status = 'error'",
               existing_nullable=True)
    op.alter_column('datasets', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'ready', 'error', name='datasetstatus'),
               server_default=sa.text("'pending'::datasetstatus"),
               existing_nullable=False)
    op.alter_column('datasets', 'columns_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Per-column schema inferred during processing',
               existing_nullable=True)
    op.alter_column('datasets', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               comment=None,
               existing_comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('datasets', 'storage_key',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='Object storage path (S3 key, GCS object name, etc.)',
               existing_nullable=False)
    op.alter_column('datasets', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Original filename as uploaded by the user',
               existing_nullable=False)
    op.alter_column('analysis_sessions', 'status',
               existing_type=postgresql.ENUM('active', 'archived', name='sessionstatus'),
               server_default=sa.text("'active'::sessionstatus"),
               existing_nullable=False)
    op.alter_column('analysis_sessions', 'goal',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='User-defined objective or hypothesis for this session',
               existing_nullable=True)
    op.alter_column('activity_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured event-specific context',
               existing_nullable=True)
    op.alter_column('activity_logs', 'description',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Human-readable summary of the event',
               existing_nullable=False)
    # ### end Alembic commands ###
