"""add validation_error to messages

Revision ID: 9071e09c1cbe
Revises: 085274df2abb
Create Date: 2026-07-01 17:31:20.544856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9071e09c1cbe'
down_revision: Union[str, None] = '085274df2abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('validation_error', sa.Text(), nullable=True, comment='Detailed error message if the generated SQL failed validation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'validation_error')
    # ### end Alembic commands ###
