"""add chart_data

Revision ID: e6a1a0d5ffef
Revises: 15b09a624cd5
Create Date: 2026-07-01 18:15:27.138767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6a1a0d5ffef'
down_revision: Union[str, None] = '15b09a624cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Automatic visualization metadata generated from execution_result'))
    op.alter_column('messages', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='AI model identifier',
               existing_comment="AI model identifier, e.g. 'gpt-4o', 'claude-3-5-sonnet-20241022'",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment="AI model identifier, e.g. 'gpt-4o', 'claude-3-5-sonnet-20241022'",
               existing_comment='AI model identifier',
               existing_nullable=True)
    op.drop_column('messages', 'chart_data')
    # ### end Alembic commands ###
